Cargo.lock
Cargo.toml
Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
src/iroh.udl
src/node.rs

output isn't very glamorous, but at least lets you see what's going on.
I've updated to not show ANSI after this screenshot was taken:

feat: add 'set_log_level' to control iroh logging from other languages

---

Cargo.lock
Cargo.toml
Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
src/iroh.udl
src/node.rs

this changes a bunch of method names.
one of the concerns with using the "real" method names: adding support for various arguments & options to FFI bindings will be breaking changes. We already have this problem with stuff like the iroh node constructor (which currently accepts no configuration, so I vote we just don't worry about it, and ship breaking stuf

Iroh v0.6.0 update

---

Cargo.toml

This version is used by the python bindings.  Since this is a new
release bump them to the next number.  We don't currently match the
version number with iroh's version number.

build: bump Cargo.toml version

---

DEVELOPERS.md
Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
README.md
go/go.mod
go/go.sum
go/iroh/iroh.go
go/iroh/iroh.h
go/net_test.go
python/net_test.py
src/error.rs
src/iroh.udl
src/lib.rs
src/net.rs
src/node.rs

- Add `SocketAddr`, `Ipv4Addr`, `Ipv6Addr`, `SocketAddrV4`, and `SocketAddrV6` to the api to maintain type safety. These also act as a very good "first example" on how to handle translations between the rust API and the ffi API.
- Added instructions on the expected translations to the README.md. closes #54
- Added python tests
- Added go tests
- Added instructions on how to structure and run the go and python tests

refactor: `Socketaddr`

---

Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
go/doc_test.go
go/iroh/iroh.go
go/iroh/iroh.h
go/main.go
python/doc_test.py
src/doc.rs
src/iroh.udl
src/node.rs

I erroneously took out the way to get the `hash` from the entry, and this PR puts it back in!
This adds a breaking change that converts `IrohNode::doc_new` and `IrohNode::author_new` to `Iroh::doc_create` and `Iroh::author_create`, to reflect the iroh core API.

feat: restore `Entry::content_hash` & `Entry::content_len`

---

IrohLib/Sources/IrohLib/IrohLib.swift
README.python.md
go/iroh/iroh.go
go/iroh/iroh.h
src/blob.rs
src/doc.rs
src/iroh.udl
src/lib.rs
src/node.rs

docs are not currently implemented for go, but you can view the docs through python by running `python -m pydoc -b` to get an html representation of the python doc book.

add doc strings to each struct, trait, method, and function

---

Cargo.lock
Cargo.toml
Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
iroh-go/iroh/iroh.go
iroh-go/iroh/iroh.h
src/blob.rs
src/doc.rs
src/iroh.udl

- adds `Collection`
- adds `IrohNodeNode::blobs_read_at_to_bytes`
- adds `IrohNode::blobs_get_collection`
closes #93

Adjust API to match `iroh` main, in prep for `0.13.0` release

---

.github/workflows/wheels.yml
Cargo.lock
README.python.md
RELEASE.md
python/main.py

Also fixes some typos and upgrades the `iroh-ffi/python/main.py` file to use the upgraded API
closes #72

docs: add instructions on how to release iroh python

---

src/doc.rs
src/iroh.udl

- query latest_single_per_key exact & prefix
- add timestamp to entry

feat(docs): add some helpers

---

.github/workflows/wheels.yml

Github Actions bumped runner images to default `macOS-latest` to macOS 14 and running on arm based (m1) macs. This ensures the `x86_64` builds remain on `macOS-13`

fix(ci): ensure mac uses correct image to build wheels

---

.github/workflows/ci.yml

https://github.com/actions/setup-python/releases
https://github.com/n0-computer/iroh-ffi/actions
The GitHub Actions run kicks out this warning...
> ⚠️ Warning: Failed to set rpath for /root/actions-runner/_work/iroh-ffi/iroh-ffi/target/debug/libiroh_ffi.so: Failed to execute 'patchelf', did you install it? Hint: Try `pip install maturin[patchelf]` (or just `pip install patchelf`)
Run `pytest` in _verbose_ mode to isolate which test is running in an infinite loop --> `python -m pytest -vvv`

GitHub Actions: build_and_test_python on Python 3.12

---

.github/workflows/ci.yml

Test `python/gossip_test.py` often times out waiting for a response so until it is fixed, let's run all other pytests first.
```
pytest --ignore python/gossip_test.py
pytest -vvv python/gossip_test.py
```
https://docs.pytest.org/en/stable/example/pythoncollection.html
```
============================= test session starts ==============================
platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
rootdir: /root/actions-runner/_work/iroh-ffi/iroh-ffi
configfile: pyproject.toml
plugins: asyncio-0.23.7
asyncio: mode=Mode.STRICT
collected 14 items
python/author_test.py .                                                  [  7%]
python/blob_test.py .....                                                [ 42%]
python/doc_test.py .....                                                 [ …
```

GitHub Actions: Run all other pytest before running flaky `python/gossip_test.py`

---

DEVELOPERS.md
README.python.md
pytest.ini

* add `pytest.ini` to ignore the `lib/` folder with virtualenv pip dependencies. We do not want to run tests in there (and some tests for a lib `colorama`, some nested dependency of pytest or so,, failed for me).
* Add copy-pastable commands to python docs for getting started
* Move docs into README.python.md to not duplicate things

docs: Improve python docs and setup

---

Iroh.xcframework/ios-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/macos-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
IrohLib/Tests/IrohLibTests/IrohLibTests.swift
kotlin/author_test.kts
kotlin/blob_test.kts
kotlin/doc_test.kts
kotlin/gossip_test.kts
kotlin/iroh/iroh_ffi.kt
kotlin/node_test.kts
python/author_test.py
python/blob_test.py
python/doc_test.py
python/gossip_test.py
python/key_test.py
python/lib_test.py
python/main.py
python/node_test.py
src/author.rs
src/blob.rs
src/doc.rs
src/gossip.rs
src/node.rs
src/tag.rs

- divide structures, `fn blob_` is now `blobs().` etc
- workarounds for python reserved names `del` and `import`
- `IrohNode` is now `Iroh`
Closes #166 
```python
node = await IrohNode.persistent(dir.name)
add_outcome = await node.blobs_add_bytes(bytes)
node = await Iroh.persistent(dir.name)
add_outcome = await node.blobs().add_bytes(bytes)
```

refactor: align structure more closely with rust library

---

.github/workflows/release.yml
Cargo.toml

Stripping symbols messes with maturin. Maturin has it's own `--strip` but I first need to figure out how to remove symbols of other targets and keep them only on the maturin builds.
Release builds broke when we moved the lib name from `libiroh` to `libiroh_ffi`. IIRC that was when we did the swift setup.

fix: maturin & release builds

---

Iroh.xcframework/ios-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/macos-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
iroh-js/__test__/blob.spec.mjs
iroh-js/index.d.ts
iroh-js/src/blob.rs
kotlin/iroh/iroh_ffi.kt
src/blob.rs
src/doc.rs
src/ticket.rs

share should return a `BlobTicket` instead of the string directly, no? maybe?
I've also added a `serialize` method to `BlobTicket`, _and_ the `#[uniffi::export(Display)]` derive used by `AuthorId`. My reason for having both is `#[uniffi::export(Display)]` converts to a `description` method in swift, and it's extremely strange to use `.description` as the main "purpose" of the `BlobTicket` struct when serializing

normalize ticket handling for all bindings

---

Cargo.lock
Cargo.toml
iroh-js/__test__/node.spec.mjs
iroh-js/index.d.ts
iroh-js/index.js
iroh-js/src/author.rs
iroh-js/src/blob.rs
iroh-js/src/doc.rs
iroh-js/src/gossip.rs
iroh-js/src/net.rs
iroh-js/src/node.rs
kotlin/iroh/iroh_ffi.kt
python/blob_test.py
src/author.rs
src/blob.rs
src/doc.rs
src/gossip.rs
src/net.rs
src/node.rs
src/tag.rs

- add more options for node configuration
- add `client` constructor to connect to an existing iroh node
Closes #182

feat: expand node constructor options 

---

.github/workflows/release.yml

0.26 failed to build rust artifacts due to a failed windows build. This fixes it. Once in, I'll rebuild the artifacts.

fix(ci): windows builds on release

---

python/main.py

This fixes the code for the main.py example in the python folder to work with iroh 0.27.0
The new example code creates a single document, shares the document and prompts the user to use a secondary terminal to get the data from the document.

Update main.py example for latest iroh

---

Iroh.xcframework/ios-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/macos-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
iroh-js/__test__/blob.spec.mjs
iroh-js/__test__/gossip.spec.mjs
iroh-js/__test__/node.spec.mjs
iroh-js/index.d.ts
iroh-js/src/node.rs
kotlin/author_test.kts
kotlin/blob_test.kts
kotlin/doc_test.kts
kotlin/gossip_test.kts
kotlin/iroh/iroh_ffi.kt
kotlin/node_test.kts
python/gossip_test.py
python/node_test.py
src/doc.rs
src/node.rs

This improves the internal shutdown logic, to wait when possible for actual shutdown to complete.
- `node.shutdown` does not take an argument anymore

feat!: improve shutdown handling

---

src/ticket.rs

Adds the `NodeTicket` to the FFI crate. Basically a copy of the already existing `BlobTicket` and `DocTicket`.
I use this in an Android application of mine and it works as expected. I played with the idea of adding `from_bytes` and `to_bytes`, but ultimately decided to instead just do this small change for now as it is all I need right now.
Not sure if I need to generate any new files? Please let me know.

Add NodeTicket FFI variant

---

iroh-js/__test__/node.spec.mjs
iroh-js/index.d.ts
iroh-js/src/endpoint.rs
iroh.pyi
python/node_test.py
src/endpoint.rs
src/node.rs

I needed this information, where I only have a reference to the Endpoint, rather than the `net` API. Question, should I then also add this to the other languages?
While I was at it, I also added the py.typed functionality to make static type checkers happy.
Fixes #200

Expose node_id on Endpoint
