n0-computer/iroh-ffi

Cargo.lock
Cargo.toml
src/iroh.udl
src/node.rs

depends on https://github.com/n0-computer/iroh/pull/1417

additional api methods and simplification of the api

---

CHANGELOG.md
Cargo.lock
Cargo.toml
Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
README.md
src/iroh.udl
src/node.rs

An initial release to publish build artifacts for swift packages

Release v0.0.6

---

Cargo.lock
Cargo.toml
src/error.rs
src/iroh.udl
src/node.rs

adds
- connections
- connection_info
- list_authors

feat: update to alpha.1 and add some new methods

---

Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
src/error.rs
src/iroh.udl
src/node.rs

requesting initial review just to make sure I'm on the right track

feat: initial work on blob methods

---

.gitignore
Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
go/iroh/iroh.go
go/iroh/irohFFI.h
go/main.go
src/iroh.udl
src/node.rs

node creation with path and improved live events

---

Cargo.lock
Cargo.toml
go/doc_test.go
python/doc_test.py
src/doc.rs
src/key.rs
src/net.rs
src/node.rs

closes https://github.com/n0-computer/iroh-ffi/issues/65

chore(deps): bump iroh version

---

Cargo.lock
Cargo.toml
Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
go/blob_test.go
go/iroh/iroh.go
go/iroh/iroh.h
python/blob_test.py
python/tag_test.py
src/blob.rs
src/error.rs
src/iroh.udl
src/lib.rs
src/node.rs
src/tag.rs

Also, adds rust, go, and python tests for the `IrohNode::blobs_` methods

feat: fill out `iroh::BlobClient` api on the `IrohNode`

---

Cargo.lock
Cargo.toml
Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
README.md
go/iroh/iroh.go
go/iroh/iroh.h

also now using the merged version of uniffi-bindgen-go

feat: upgrade to uniffi@0.25

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
src/node.rs

also adjust secret key generation

fix release.yml

---

Cargo.toml

bump iroh-ffi version

---

Iroh.xcframework/ios-arm64/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/irohFFI.h
Iroh.xcframework/macos-arm64/Iroh.framework/Headers/irohFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
iroh-go/iroh/iroh.go
iroh-go/iroh/iroh.h
src/blob.rs
src/error.rs
src/iroh.udl

closes #101 
also adds `get_collection` which I guess I missed in the previous PR?!

add `create_collection` & expand `Collection` API

---

Cargo.lock
Cargo.toml
python/blob_test.py
python/doc_test.py
src/blob.rs
src/doc.rs
src/iroh.udl
src/lib.rs
src/node.rs

Update to iroh v0.13.0

---

README.md

Also, fixes broken discord link.

docs: adjusting language in README so that we do not have to update it every time we publish a release

---

Cargo.lock
Cargo.toml
python/node_test.py
src/blob.rs
src/doc.rs
src/iroh.udl
src/node.rs
src/ticket.rs

update to iroh v0.15.0

---

README.md
python/author_test.py
src/author.rs
src/iroh.udl

closes #126 
TODO: add a python test

feat(author): add v0.14.0 author API methods

---

IrohLib.podspec
IrohLibFramework.podspec

need cocoapods support to get up into expo dev work

feat: cocoapods specs

---

DEVELOPERS.md
README.md
RELEASE.md

```diff
- commited
+ committed
- verison
+ version
```
And other changes...
https://pypi.org/project/codespell/

Fix typos in DEVELOPERS.md, README.md, and RELEASE.md

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
Iroh.xcframework/ios-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/macos-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
IrohLib.podspec
IrohLib/Sources/IrohLib/IrohLib.swift
IrohLibFramework.podspec
kotlin/gossip_test.kts
kotlin/iroh/iroh_ffi.kt
python/gossip_test.py
src/gossip.rs

~~Testing if https://github.com/n0-computer/iroh/pull/2570 helps on CI~~
Updates to `0.22.0`
TODO: update to released version once it lands on crates.io

feat: update to iroh@0.22.

---

Cargo.lock
Cargo.toml
IrohLib.podspec
iroh-js/Cargo.toml
iroh-js/npm/android-arm-eabi/package.json
iroh-js/npm/android-arm64/package.json
iroh-js/npm/darwin-arm64/package.json
iroh-js/npm/darwin-universal/package.json
iroh-js/npm/linux-arm-gnueabihf/package.json
iroh-js/npm/linux-arm-musleabihf/package.json
iroh-js/npm/linux-arm64-gnu/package.json
iroh-js/npm/linux-arm64-musl/package.json
iroh-js/npm/linux-x64-gnu/package.json
iroh-js/npm/linux-x64-musl/package.json
iroh-js/npm/win32-arm64-msvc/package.json
iroh-js/npm/win32-x64-msvc/package.json
iroh-js/package.json
iroh-js/src/lib.rs
iroh-js/test/node.mjs
iroh-js/yarn.lock
kotlin/lib/src/main/kotlin/computer/iroh/iroh_ffi.kt
pyproject.toml
src/lib.rs

chore: upgrade to `iroh@v0.31.0`

---

Iroh.xcframework/ios-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/ios-arm64_x86_64-simulator/Iroh.framework/Headers/iroh_ffiFFI.h
Iroh.xcframework/macos-arm64/Iroh.framework/Headers/iroh_ffiFFI.h
IrohLib/Sources/IrohLib/IrohLib.swift
iroh-js/index.d.ts
iroh-js/src/blob.rs
iroh-js/test/blob.mjs
kotlin/lib/src/main/kotlin/computer/iroh/iroh_ffi.kt
kotlin/lib/src/test/kotlin/computer/iroh/BlobTest.kt
python/blob_test.py
src/blob.rs

feat: add has and status blobs methods

---

python/main.py

In line 63, content_bytes() did not exist in Entry class. I just took line 118 from doc_test.py.
Don't think it'll cause any issues.

Update main.py, content_bytes() did not exist in Entry class.
